In [2]:
print("hello world")

hello worlsdfsdfd


In [3]:
# int variable
x = 5
print (x, type(x))

5 <class 'int'>


In [4]:
# Sets
text = "Learn ML with Made With ML"
print (set(text))
print (set(text.split(" ")))

{'M', 'd', 'w', 't', 'i', 'e', 'r', 'a', 'n', ' ', 'L', 'h', 'W'}
{'With', 'Made', 'ML', 'with', 'Learn'}


In [5]:
print(text.split("M"))

['Learn ', 'L with ', 'ade With ', 'L']


In [8]:
# Let's try using decorators

def logMessage(function):
    def wrapper(*args, **kwargs):
        x = kwargs.pop("x")
        print(f"Starting Log. Value of x is: {x}")
        x = function(*args, **kwargs, x=x)
        
        print(f"End of the message value of x is {x}")

        return x
    return wrapper

@logMessage
def runFunction(x='Homer', y = "Illiad"):
    x = x+' '+y
    return x

runFunction(x='Homer')
    

Starting Log. Value of x is: Homer
End of the message value of x is Homer Illiad


'Homer Illiad'

In [6]:
import numpy as np

x = np.array([[[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3]],
            [[10, 10, 10, 10], [20, 20, 20, 20], [30, 30, 30, 30]]])
print ("x:\n", x)
print ("x.shape: ", x.shape)

x:
 [[[ 1  1  1  1]
  [ 2  2  2  2]
  [ 3  3  3  3]]

 [[10 10 10 10]
  [20 20 20 20]
  [30 30 30 30]]]
x.shape:  (2, 3, 4)


In [7]:
x.reshape(3,1,8)

array([[[ 1,  1,  1,  1,  2,  2,  2,  2]],

       [[ 3,  3,  3,  3, 10, 10, 10, 10]],

       [[20, 20, 20, 20, 30, 30, 30, 30]]])

In [20]:
import pandas as pd

# Read from CSV to Pandas DataFrame
url = 'https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv'
df = pd.read_csv(url, header=0)

In [22]:
df

Survived  Pclass                                               Name  \
0           0       3                             Mr. Owen Harris Braund   
1           1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...   
2           1       3                              Miss. Laina Heikkinen   
3           1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle   
4           0       3                            Mr. William Henry Allen   
..        ...     ...                                                ...   
882         0       2                               Rev. Juozas Montvila   
883         1       1                        Miss. Margaret Edith Graham   
884         0       3                     Miss. Catherine Helen Johnston   
885         1       1                               Mr. Karl Howell Behr   
886         0       3                                 Mr. Patrick Dooley   

        Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  
0      male  22.0                        1                        0   7.2500  
1    female  38.0                        1                        0  71.2833  
2    female  26.0                        0                        0   7.9250  
3    female  35.0                        1                        0  53.1000  
4      male  35.0                        0                        0   8.0500  
..      ...   ...                      ...                      ...      ...  
882    male  27.0                        0                        0  13.0000  
883  female  19.0                        0                        0  30.0000  
884  female   7.0                        1                        2  23.4500  
885    male  26.0                        0                        0  30.0000  
886    male  32.0                        0                        0   7.7500  

[887 rows x 8 columns]

In [23]:
!ls -l


total 1000
-rw-r--r--  1 raghav  staff   12247 Aug 14 22:21 prereqs.ipynb
-rw-r--r--@ 1 raghav  staff  496619 Aug 14 22:15 titanic.csv
drwxr-xr-x  8 raghav  staff     256 Aug 14 15:44 venv
